config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "foods#index"
  resources :foods
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :foods, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: %i[edit update destroy]

  def index
    @foods = Food.includes(:user).order(:created_at)
  end

  def new
    @food = Food.new
  end

  def create
    food = current_user.foods.create!(food_params)
    redirect_to food
  end

  def show
    @food = Food.find(params[:id])
  end

  def edit; end

  def update
    @food.update!(food_params)
    redirect_to @food
  end

  def destroy
    @food.destroy
    redirect_to root_path
  end

  private

  def set_food
    @food = current_user.foods.find_by(id: params[:id])
    redirect_to root_path, alert: "権限がありません" if @food.nil?
  end

  def food_params
    params.require(:food).permit(:name, :comment)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/foods/_food.html.erb
<div>
  <p>【メールアドレス】<%= food.user.email %></p>
  <p>【食品名】<%= food.name %></p>
  <p><%= link_to "詳細", food_path(food) %></p>
  <% if current_user.id == food.user_id %>
  <p>
    <%= link_to "編集", edit_food_path(food) %>
    <%= link_to "削除", food_path(food), method: :delete, data: { confirm: "削除しますか？" } %>
  </p>
  <% end %>
</div>
<hr>

app/views/foods/_form.html.erb
<%= form_with model: @food, local: true do |f| %>
<p>
  <%= f.label :name %>
  <%= f.text_field :name, required: true %>
</p>
<P>
  <%= f.label :comment %>
  <%= f.text_area :comment %>
</P>
<p>
  <%= f.submit "送信" %>
</p>
<% end %>

app/views/foods/edit.html.erb
<h1>編集</h1>
<%= render "form" %>

app/views/foods/index.html.erb
<h1>お勧め商品 投稿一覧</h1>
<%= render @foods %>

app/views/foods/new.html.erb
<h1>新規投稿</h1>
<%= render "form" %>

app/views/foods/show.html.erb
<h1>投稿詳細</h1>
<p>【メールアドレス】<%= @food.user.email %></p>
<p>【食品名】<%= @food.name %></p>
<p>【コメント】</p>
<p><%= simple_format(h(@food.comment)) %></p>
<% if current_user.id == @food.user_id %>
<%= link_to "編集", edit_food_path(@food) %>
<%= link_to "削除", food_path(@food), method: :delete, data: { confirm: "削除しますか？" } %>
<% end %>
<%= link_to "投稿一覧へ", foods_path %>

app/views/layouts/_header.html.erb
<% if user_signed_in? %>
<%= link_to "一覧ページ", root_path %>
<%= link_to "新規投稿ページ", new_food_path %>
<%= link_to "アカウント編集", edit_user_registration_path %>
<%= link_to "ログアウト", destroy_user_session_path, method: :delete, data: { confirm: "ログアウトしますか？"} %>
<%= "【ログイン中のアドレス】#{current_user.email}"%>
<% else %>
<%= link_to "新規登録", new_user_registration_path %>
<%= link_to "ログイン", new_user_session_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>RecommendedFoodApp</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <header>
    <%= render "layouts/header" %>
    <hr>
  </header>
  <%= yield %>
</body>

</html>